name: "Format Check"

on:
  push:
    branches:
      - 'main'
    tags: '*'
  pull_request:

permissions:
  contents: read
  actions: write
  pull-requests: write

jobs:
  format-check:
    name: "Format Check"
    uses: "ITensor/ITensorActions/.github/workflows/FormatCheck.yml@main"
